### ISSUE TITLE
Source des données?

### ISSUE THREAD

**Issue by PMassicotte** [jhroy/theses#1]
Bonjour @jhroy. Est-ce qu'il est possible de savoir comment avoir accès aux sources des données? J'aimerais mettre à jour la liste.

Cordialement,
Phil

**Comment by jhroy** [comment]
Bonsoir @PMassicotte!
J'avais publié toute ma démarche ici:
http://jhroy.ca/2016/11/combien-de-pages-pour-une-these-ou-un-memoire/
Mon blogue pointait vers Github, mais pas l'inverse. Je vais corriger cela.
Si c'était à refaire, cependant, je puiserais maintenant dans la section d'Érudit consacrée aux thèses et mémoires, qui n'existait pas en 2016:
https://www.erudit.org/fr/theses/
En espérant avoir pu vous aider :)
JHR

**Comment by PMassicotte** [comment]
Merci beaucoup pour les info! Je vais regarder du Érudit, je ne conaissais pas :)
